import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { DOCTOR, WHATSAPP_LINK } from '../data/site';
import { useSeo, breadcrumbJsonLd, doctorJsonLd, websiteJsonLd } from '../lib/seo';

type Mode = 'gregorian' | 'hijri';
const MONTHS=['محرم','صفر','ربيع الأول','ربيع الثاني','جمادى الأولى','جمادى الآخرة','رجب','شعبان','رمضان','شوال','ذو القعدة','ذو الحجة'];
const WEEK_INFO:Record<number,string>={4:'بداية مبكرة للحمل وقد يصبح اختبار الحمل إيجابيًا.',8:'تتطور أعضاء وملامح أساسية بسرعة.',12:'تكتمل مرحلة مهمة من التطور المبكر.',16:'يستمر نمو الجنين وتزداد أهمية المتابعة.',20:'منتصف الحمل تقريبًا وقد تكون متابعة النمو والتصوير مهمة.',24:'يستمر نضج أجهزة الجسم والمتابعة المنتظمة.',28:'يبدأ الثلث الثالث ويزداد التركيز على النمو والحركة.',32:'يستمر اكتساب الوزن والنضج الوظيفي.',36:'مرحلة متقدمة من الحمل والاستعداد للولادة.',40:'موعد تقريبي لاكتمال الحمل وليس موعدًا حتميًا للولادة.'};
function addDays(d:Date,n:number){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function dateOnly(v:string){const [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)}
function gDate(d:Date){return new Intl.DateTimeFormat('ar-SA',{calendar:'gregory',year:'numeric',month:'long',day:'numeric'}).format(d)}
function hDate(d:Date){return new Intl.DateTimeFormat('ar-SA-u-ca-islamic-umalqura',{year:'numeric',month:'long',day:'numeric'}).format(d)}
function weekday(d:Date){return new Intl.DateTimeFormat('ar-SA',{weekday:'long'}).format(d)}
function hijriToGregorian(y:number,m:number,d:number){const jd=Math.floor((11*y+3)/30)+354*y+30*m-Math.floor((m-1)/2)+d+1948440-385;const b=jd+32044,c=Math.floor((4*b+3)/146097),e0=b-Math.floor(146097*c/4),e=Math.floor((4*e0+3)/1461),f=e0-Math.floor(1461*e/4),g=Math.floor((5*f+2)/153);const gd=f-Math.floor((153*g+2)/5)+1,gm=g+3-12*Math.floor(g/10),gy=100*c+e-4800+Math.floor(g/10);return new Date(Date.UTC(gy,gm-1,gd))}

export default function PregnancyCalculatorPage(){
 const [mode,setMode]=useState<Mode>('gregorian'),[date,setDate]=useState(''),[hy,setHy]=useState(1447),[hm,setHm]=useState(1),[hd,setHd]=useState(1),[lmp,setLmp]=useState<Date|null>(null),[error,setError]=useState('');
 useSeo({title:'طريقة حساب عمر الحمل | حاسبة الحمل الدقيقة | د. هيثم الخطيب',description:'حاسبة الحمل الدقيقة لحساب عمر الحمل وموعد الولادة المتوقع بالأسابيع والأشهر، مع التاريخ الميلادي والهجري وجدول مبسط لمراحل الحمل.',canonicalPath:'/طريقة-حساب-عمر-الحمل',image:'https://femseha.com/saudi-cytotec-logo.webp',jsonLd:[websiteJsonLd(),doctorJsonLd(),breadcrumbJsonLd([{name:'الرئيسية',href:'/'},{name:'حاسبة الحمل الدقيقة',href:'/طريقة-حساب-عمر-الحمل'}]),{'@context':'https://schema.org','@type':'WebApplication',name:'حاسبة الحمل الدقيقة',applicationCategory:'HealthApplication',operatingSystem:'Web',url:'https://femseha.com/طريقة-حساب-عمر-الحمل'}]});
 const result=useMemo(()=>{if(!lmp)return null;const n=new Date(),s=new Date(lmp.getFullYear(),lmp.getMonth(),lmp.getDate()),t=new Date(n.getFullYear(),n.getMonth(),n.getDate()),elapsed=Math.floor((t.getTime()-s.getTime())/86400000);if(elapsed<0)return null;const days=Math.min(elapsed,280),week=Math.min(40,Math.floor(days/7)+1),day=days%7,due=addDays(s,280),conception=addDays(s,14),remaining=Math.max(0,280-days);return{week,day,due,conception,remaining,month:Math.min(9,Math.floor(days/30.44)+1),trimester:week<=13?'الثلث الأول':week<=27?'الثلث الثاني':'الثلث الثالث'}},[lmp]);
 function calculate(){setError('');if(mode==='gregorian'){if(!date){setError('اختاري أول يوم من آخر دورة شهرية.');return}const d=dateOnly(date);if(d>new Date()){setError('لا يمكن اختيار تاريخ في المستقبل.');return}setLmp(d);return}const d=hijriToGregorian(hy,hm,hd);if(d>new Date()){setError('التاريخ الهجري المختار يبدو في المستقبل.');return}setLmp(new Date(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()))}
 return <div className="min-h-screen bg-gradient-to-b from-rose-50 via-white to-sky-50" dir="rtl">
  <div className="bg-emerald-600 text-white py-2 px-4 text-sm font-bold"><div className="max-w-7xl mx-auto flex justify-between gap-3 flex-wrap"><span>حاسبة الحمل الدقيقة — بإشراف {DOCTOR.name}</span><a href={WHATSAPP_LINK} target="_blank" rel="noopener noreferrer" className="hover:underline">💚 تواصل عبر واتساب للاستشارة</a></div></div>
  <section className="bg-gradient-to-l from-rose-100 via-white to-pink-50 border-b border-rose-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 py-9 lg:py-12 grid lg:grid-cols-[1fr_1.35fr_1fr] items-center gap-7">
   <div className="hidden lg:flex justify-center"><img src="/images/dr-haitham-hero.webp" alt="د. هيثم الخطيب استشاري طب النساء والتوليد" width={768} height={768} loading="eager" className="max-h-80 w-auto object-contain rounded-3xl"/></div>
   <div className="text-center"><div className="inline-flex items-center gap-3 bg-white border border-rose-200 rounded-full px-4 py-2 shadow-sm mb-4"><img src="/saudi-cytotec-logo-96w.webp" alt="شعار FemSeha" width={48} height={48} className="w-10 h-10 rounded-xl"/><span className="font-black text-rose-700">FemSeha | فيم صحة</span></div><h1 className="text-3xl sm:text-4xl lg:text-5xl font-black text-slate-950 leading-tight">طريقة حساب عمر الحمل<br/><span className="text-rose-600">حاسبة الحمل الدقيقة</span></h1><p className="mt-5 text-lg text-slate-800 leading-loose font-medium">احسبي عمر الحمل وموعد الولادة المتوقع وتاريخ الإخصاب التقريبي والأسابيع والأيام المتبقية بالتاريخ الميلادي أو الهجري بسهولة.</p></div>
   <div className="bg-white rounded-3xl p-4 shadow-xl border border-rose-100"><img src="/images/whatsapp-consultation.webp" alt="استشارة طبية عبر واتساب مع د. هيثم الخطيب" width={1024} height={683} loading="eager" fetchPriority="high" className="w-full rounded-2xl mb-4"/><a href={WHATSAPP_LINK} target="_blank" rel="noopener noreferrer" className="w-full inline-flex justify-center items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl px-4 py-3.5 font-black text-base shadow">💬 تواصلي عبر واتساب مع د. هيثم الخطيب</a><p className="text-xs text-slate-700 text-center mt-3">استشارة خاصة — لا تشاركي معلومات صحية حساسة في التعليقات العامة.</p></div>
  </div></section>
  <main className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
   <nav aria-label="مسار التنقل" className="text-sm text-slate-600 mb-5"><Link to="/" className="text-sky-700 hover:underline">الرئيسية</Link><span className="mx-2">‹</span><b>حاسبة الحمل الدقيقة</b></nav>
   <section className="bg-white rounded-3xl border border-rose-200 shadow-xl p-5 sm:p-8"><h2 className="text-2xl sm:text-3xl font-black text-slate-950">أدخلي تاريخ أول يوم من آخر دورة شهرية</h2><p className="text-slate-700 text-base mt-2">اختاري التاريخ الميلادي أو الهجري ثم اضغطي «احسبي الآن».</p>
    <div className="flex justify-center gap-2 my-6"><button type="button" onClick={()=>setMode('gregorian')} className={mode==='gregorian'?'px-6 py-3 rounded-xl bg-rose-600 text-white font-bold':'px-6 py-3 rounded-xl bg-rose-50 text-rose-800 font-bold border border-rose-200'}>بالتاريخ الميلادي</button><button type="button" onClick={()=>setMode('hijri')} className={mode==='hijri'?'px-6 py-3 rounded-xl bg-rose-600 text-white font-bold':'px-6 py-3 rounded-xl bg-rose-50 text-rose-800 font-bold border border-rose-200'}>بالتاريخ الهجري</button></div>
    {mode==='gregorian'?<div className="grid md:grid-cols-[1fr_auto] gap-4 items-end"><label><span className="block font-bold text-slate-900 mb-2">أول يوم من آخر دورة — ميلادي</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="w-full rounded-xl border border-slate-300 px-4 py-3.5 text-base"/></label><button type="button" onClick={calculate} className="bg-rose-600 hover:bg-rose-700 text-white px-8 py-3.5 rounded-xl font-black">احسبي الآن</button></div>:<div className="grid sm:grid-cols-4 gap-3 items-end"><label><span className="block font-bold mb-2">اليوم</span><select value={hd} onChange={e=>setHd(Number(e.target.value))} className="w-full rounded-xl border px-4 py-3.5 text-base">{Array.from({length:30},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label><label><span className="block font-bold mb-2">الشهر الهجري</span><select value={hm} onChange={e=>setHm(Number(e.target.value))} className="w-full rounded-xl border px-4 py-3.5 text-base">{MONTHS.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></label><label><span className="block font-bold mb-2">السنة</span><input type="number" min={1350} max={1500} value={hy} onChange={e=>setHy(Number(e.target.value))} className="w-full rounded-xl border px-4 py-3.5 text-base"/></label><button type="button" onClick={calculate} className="bg-rose-600 hover:bg-rose-700 text-white px-6 py-3.5 rounded-xl font-black">احسبي الآن</button></div>}
    {error&&<p role="alert" className="mt-4 bg-red-50 border border-red-200 text-red-800 rounded-xl p-4 font-bold">{error}</p>}
   </section>
   {result&&<section className="mt-7"><h2 className="text-2xl sm:text-3xl font-black text-rose-800 text-center mb-5">نتائج حاسبة الحمل</h2><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-4">{[['عمر الحمل الحالي',result.week+' أسبوع و'+result.day+' يوم'],['الشهر الحالي','الشهر '+result.month],['الثلث الحالي',result.trimester],['الأسابيع المتبقية',Math.ceil(result.remaining/7)+' أسبوع تقريبًا'],['الأيام المتبقية للولادة',result.remaining+' يوم تقريبًا']].map(([label,value])=><div key={label} className="bg-white rounded-2xl border border-rose-100 p-5 text-center shadow-sm"><div className="text-rose-500 text-2xl">♡</div><h3 className="font-bold text-slate-700">{label}</h3><p className="font-black text-slate-950 text-lg mt-2">{value}</p></div>)}</div><div className="grid md:grid-cols-2 gap-4 mt-4"><div className="bg-white rounded-2xl border p-5"><b>موعد الولادة المتوقع — ميلادي</b><p className="text-xl font-bold text-rose-700 mt-2">{gDate(result.due)}</p></div><div className="bg-white rounded-2xl border p-5"><b>موعد الولادة المتوقع — هجري</b><p className="text-xl font-bold text-emerald-700 mt-2">{hDate(result.due)}</p></div><div className="bg-white rounded-2xl border p-5"><b>تاريخ الإخصاب التقريبي</b><p className="font-bold mt-2">{gDate(result.conception)} — {hDate(result.conception)}</p></div><div className="bg-white rounded-2xl border p-5"><b>يوم الولادة المتوقع</b><p className="font-bold mt-2">{weekday(result.due)}</p></div></div></section>}
   <section className="mt-8 grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Link to="/articles/early-pregnancy-symptoms-guide" className="bg-white rounded-2xl border p-5 shadow-sm hover:border-rose-300"><b className="block text-rose-700 text-lg">أعراض الحمل المبكرة</b><span>العلامات المبكرة والتوقيت.</span></Link><Link to="/articles/home-pregnancy-test-accuracy" className="bg-white rounded-2xl border p-5 shadow-sm hover:border-rose-300"><b className="block text-rose-700 text-lg">اختبار الحمل المنزلي</b><span>التوقيت الأدق وتفسير النتائج.</span></Link><Link to="/articles/pregnancy-danger-signs-emergency" className="bg-white rounded-2xl border p-5 shadow-sm hover:border-rose-300"><b className="block text-rose-700 text-lg">علامات الخطر في الحمل</b><span>متى تحتاجين إلى رعاية عاجلة؟</span></Link><Link to="/consultation" className="bg-white rounded-2xl border p-5 shadow-sm hover:border-rose-300"><b className="block text-rose-700 text-lg">الاستشارة الطبية</b><span>تواصلي مع د. هيثم الخطيب.</span></Link></section>

   <section className="mt-8 bg-white rounded-3xl border border-rose-100 p-6 sm:p-9"><div className="flex items-center gap-4 mb-5"><img src="/saudi-cytotec-logo-96w.webp" alt="شعار FemSeha" width={64} height={64} className="w-14 h-14 rounded-2xl shadow"/><div><h2 className="text-2xl sm:text-3xl font-black text-rose-800">ما هي حاسبة الحمل الدقيقة؟</h2><p className="text-slate-600 font-medium">طريقة مبسطة لفهم عمر الحمل وموعد الولادة المتوقع</p></div></div><p className="text-slate-800 text-base leading-loose mb-4">حاسبة الحمل الدقيقة هي أداة تثقيفية تساعد المرأة على تقدير عمر الحمل بالاعتماد على تاريخ أول يوم من آخر دورة شهرية. وبناءً على هذا التاريخ يمكن تقدير عدد الأسابيع والأيام التي مضت، والشهر الحالي، والثلث الذي تمر به الحامل، إضافة إلى موعد الولادة المتوقع وتاريخ الإخصاب التقريبي. الهدف من الأداة هو تبسيط الحسابات التي قد تبدو مربكة عند متابعة الحمل، وليس استبدال المتابعة الطبية أو تحديد موعد الولادة بشكل حتمي.</p><p className="text-slate-800 text-base leading-loose">الحساب الطبي الشائع يعتمد على مدة حمل تقارب 40 أسبوعًا، أي نحو 280 يومًا من أول يوم في آخر دورة. لذلك قد يختلف العمر المحسوب عن عمر الجنين الفعلي بنحو أسبوعين تقريبًا لأن حساب عمر الحمل يبدأ من الدورة الأخيرة وليس من يوم الإخصاب. وإذا كانت الدورة غير منتظمة أو كان التاريخ غير مؤكد، فقد يحتاج الطبيب إلى الفحص أو التصوير لتقدير العمر الأنسب للمتابعة.</p></section>

   <section className="mt-7 bg-white rounded-3xl border p-6 sm:p-9"><h2 className="text-2xl sm:text-3xl font-black text-rose-800 mb-4">كيفية حساب موعد الولادة</h2><p className="text-slate-800 text-base leading-loose mb-4">لتقدير موعد الولادة المتوقع، تبدأ الحاسبة من أول يوم في آخر دورة شهرية ثم تضيف 280 يومًا تقريبًا. ويمكن تبسيط الطريقة التقليدية إلى إضافة تسعة أشهر وسبعة أيام إلى تاريخ أول يوم من آخر دورة. هذا التاريخ تقديري وليس موعدًا حتميًا؛ فقد تتم الولادة قبل الموعد أو بعده، وتختلف المتابعة حسب عمر الحمل وحالة الأم والجنين.</p><p className="text-slate-800 text-base leading-loose mb-4">إذا كانت الدورة منتظمة وكان التاريخ معروفًا، يكون الحساب الأولي سهلًا. أما إذا كان التاريخ غير واضح أو كانت الدورة غير منتظمة، فقد يراجع الطبيب التاريخ ويعتمد على الفحص أو التصوير. لذلك من الأفضل التعامل مع الناتج باعتباره موعدًا متوقعًا لا تاريخًا حتميًا.</p><p className="text-slate-800 text-base leading-loose">تعرض الصفحة الموعد بالتاريخ الميلادي والهجري، وتعرض كذلك يوم الأسبوع المتوقع وعدد الأيام والأسابيع المتبقية، حتى تحصل المرأة على صورة واضحة دون إجراء عمليات حسابية يدوية.</p></section>

   <section className="mt-7 grid md:grid-cols-2 gap-6"><div className="bg-white rounded-3xl border p-6"><h2 className="text-2xl font-black text-rose-800 mb-4">حساب الحمل بالأسابيع</h2><p className="text-slate-800 text-base leading-loose">متابعة الحمل بالأسابيع شائعة لأن كثيرًا من الفحوصات ومراحل نمو الجنين ترتبط بعمر الحمل الأسبوعي. عندما تدخلين تاريخ آخر دورة، تحسب الأداة الأيام المنقضية ثم تحولها إلى أسابيع وأيام. يساعد ذلك على معرفة المرحلة الحالية بسرعة، مع تذكير بأن الحساب تقديري وأن التقييم الطبي قد يعدّل العمر عند الحاجة.</p></div><div className="bg-white rounded-3xl border p-6"><h2 className="text-2xl font-black text-rose-800 mb-4">حاسبة الحمل بالأشهر</h2><p className="text-slate-800 text-base leading-loose">تستخدم النساء الأشهر لفهم المرحلة العامة للحمل، بينما تستخدم المتابعة الطبية الأسابيع بصورة أكثر دقة. تعرض الحاسبة الشهر التقريبي والثلث الحالي وتوضح ما تبقى تقريبًا حتى الموعد المتوقع. لا ينبغي اعتبار كل شهر أربعة أسابيع بالضبط لأن الشهر التقويمي يختلف في عدد أيامه.</p></div></section>

   <section className="mt-7 bg-emerald-50 rounded-3xl border border-emerald-100 p-6 sm:p-9"><h2 className="text-2xl sm:text-3xl font-black text-emerald-900 mb-4">حساب الحمل بالهجري</h2><p className="text-slate-800 text-base leading-loose mb-4">تتيح الصفحة إدخال تاريخ آخر دورة بالهجري إلى جانب الميلادي. عند عرض النتائج، تستخدم التواريخ المحولة من التاريخ الميلادي تقويم أم القرى المتاح في المتصفح. أما إدخال التاريخ الهجري داخل الأداة فيعتمد تحويلًا حسابيًا، ولذلك قد يظهر فرق يوم واحد عن بعض جداول الرؤية أو التقويمات المحلية. عند وجود موعد طبي رسمي، اعتمدي التاريخ الذي يثبته الطبيب أو الجهة الصحية.</p><p className="text-slate-800 text-base leading-loose">لا تحتاجين إلى إجراء التحويل يدويًا قبل قراءة النتيجة. اختاري اليوم والشهر والسنة ثم اضغطي «احسبي الآن» لتظهر النتائج الأساسية، ويمكنك الاحتفاظ بالتاريخين للمواعيد والمتابعة.</p></section>

   <section className="mt-7 bg-white rounded-3xl border overflow-hidden"><div className="p-6 border-b"><h2 className="text-2xl sm:text-3xl font-black text-rose-800">جدول مبسط لمراحل الحمل ونمو الجنين بالأسابيع</h2><p className="text-slate-700 mt-2">معلومات عامة للتثقيف وليست قياسات تشخيصية لوزن أو طول الجنين.</p></div><div className="overflow-x-auto"><table className="w-full text-right"><thead className="bg-rose-100"><tr><th className="p-4 font-black">الأسبوع</th><th className="p-4 font-black">المرحلة</th><th className="p-4 font-black">شرح مبسط</th></tr></thead><tbody>{[4,8,12,16,20,24,28,32,36,40].map(w=><tr key={w} className="border-t"><td className="p-4 font-black text-rose-700">الأسبوع {w}</td><td className="p-4 font-bold">{w<14?'الثلث الأول':w<28?'الثلث الثاني':'الثلث الثالث'}</td><td className="p-4 text-slate-800 leading-loose">{WEEK_INFO[w]}</td></tr>)}</tbody></table></div></section>

   <section className="mt-7 bg-white rounded-3xl border p-6 sm:p-9"><h2 className="text-2xl sm:text-3xl font-black text-rose-800 mb-4">كيف تتابعين الحمل بعد معرفة عمر الحمل؟</h2><p className="text-slate-800 text-base leading-loose mb-4">بعد معرفة عمر الحمل والموعد المتوقع للولادة، من المفيد تنظيم المواعيد الطبية والفحوصات المناسبة لكل مرحلة. لا يعتمد القرار الطبي على رقم الأسبوع وحده؛ فالعمر الصحي للأم، والأعراض، ونتائج الفحوصات، ونمو الجنين والتاريخ الطبي كلها عوامل تدخل في المتابعة. إذا كان لديك ألم شديد أو نزيف أو دوخة شديدة أو أي علامة غير معتادة، فلا تنتظري نتيجة الحاسبة للحصول على الرعاية.</p><p className="text-slate-800 text-base leading-loose">يمكنك قراءة <Link to="/articles/early-pregnancy-symptoms-guide" className="text-rose-700 font-bold hover:underline">دليل أعراض الحمل المبكرة</Link>، و<Link to="/articles/home-pregnancy-test-accuracy" className="text-rose-700 font-bold hover:underline">دليل اختبار الحمل المنزلي</Link>، والتعرف على <Link to="/articles/pregnancy-danger-signs-emergency" className="text-rose-700 font-bold hover:underline">علامات الخطر في الحمل</Link>، أو الانتقال إلى <Link to="/consultation" className="text-rose-700 font-bold hover:underline">الاستشارة الطبية مع د. هيثم الخطيب</Link>.</p></section>

   <section className="mt-8 bg-white rounded-3xl border border-emerald-200 shadow-sm p-6 sm:p-9 text-center"><img src="/images/whatsapp-consultation.webp" alt="استشارة طبية خاصة عبر واتساب مع د. هيثم الخطيب" width={1024} height={683} loading="lazy" className="max-w-xl w-full mx-auto rounded-2xl mb-6"/><h2 className="text-2xl sm:text-3xl font-black text-slate-950">هل لديكِ سؤال عن الحمل أو موعد الولادة؟</h2><p className="text-slate-700 text-base leading-loose max-w-2xl mx-auto mt-3 mb-5">إذا كانت لديك نتيجة فحص أو سؤال عن عمر الحمل أو اختلاف بين التاريخ المتوقع ونتائج المتابعة، يمكنك طلب استشارة طبية مباشرة.</p><a href={WHATSAPP_LINK} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-3 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl px-8 py-4 font-black text-lg shadow-lg">💬 تواصلي عبر واتساب مع د. هيثم الخطيب</a></section>

   <section className="mt-8 bg-slate-900 text-white rounded-3xl p-6 sm:p-9"><h2 className="text-2xl font-black mb-4">تنبيه طبي مهم</h2><p className="text-slate-200 text-base leading-loose">هذه الحاسبة أداة تثقيفية لحساب عمر الحمل والموعد المتوقع للولادة، وليست تشخيصًا أو بديلًا عن متابعة طبيب النساء والتوليد. قد يحتاج الطبيب إلى تعديل عمر الحمل أو الموعد بناءً على التاريخ السريري والفحص والتصوير. عند وجود نزيف شديد، ألم شديد أو مفاجئ، إغماء، دوخة شديدة، ألم كتف مع أعراض الحمل، حرارة مرتفعة أو تدهور سريع، اطلبي الرعاية الطبية العاجلة.</p></section>
  </main>
 </div>;
}